import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import Container from "@mui/material/Container";
import theme from "../theme";
import NextProvider from "./providers";
import ServerHeader from "../components/header/initialSession";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ntialiased`}>
        <NextProvider>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <ThemeProvider theme={theme}>
              <Container maxWidth="lg">
                <ServerHeader />
                {children}
              </Container>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </NextProvider>
      </body>
    </html>
  );
}
